trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone --recursive https://github.com/armory3d/iron_examples
    git clone --recursive https://github.com/kode/Kha.git iron_examples/mesh/Kha
    git clone https://github.com/kode/nodejs_bin.git iron_examples/mesh/nodejs_bin
    cd iron_examples/mesh
    nodejs_bin/node-linux64 Kha/make.js krom
