version: 1.0.{build}
platform:
  - x64
  - x86
environment:
  matrix:
  - platform_name: windows
  - platform_name: windowsapp
before_build:
  - git submodule update --init --recursive
  - git clone https://github.com/Kode/nodejs_bin.git
  - nodejs_bin\node.exe make.js %platform_name% --kore . --from Tests/Empty --visualstudio vs2015 --noshaders
  - copy msbuild.rsp build\msbuild.rsp
build:
  project: build\Empty.sln
  verbosity: minimal